# GitHub Pages configuration
title: EARSeL EnMAP Tutorials
description: EnMAP Tutorials for 14th EARSeL Workshop on Imaging Spectroscopy

theme: just-the-docs
source: docs
url: https://enmap-box.github.io/earsel2026_tutorials

aux_links:
  Template Repository: https://enmap-box.github.io/earsel2026_tutorials/
